# Generated by Django 3.1 on 2021-03-06 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('flight_number', models.PositiveSmallIntegerField()),
                ('boarding_gate', models.PositiveSmallIntegerField()),
                ('passengers_limit', models.PositiveSmallIntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='flights.city')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origins', to='flights.city')),
            ],
            options={
                'verbose_name': 'flight',
                'verbose_name_plural': 'flights',
            },
        ),
        migrations.CreateModel(
            name='FlightStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'flight status',
                'verbose_name_plural': 'flight statuses',
            },
        ),
        migrations.CreateModel(
            name='PassengerByFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'passenger by flight',
                'verbose_name_plural': 'passengers by flight',
            },
        ),
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightstatus'),
        ),
    ]
