# Generated by Django 3.1 on 2021-03-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='flightstatus',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
