# Generated by Django 3.1 on 2021-03-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20210306_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='boarding_gate',
            field=models.CharField(max_length=5),
        ),
    ]
